- hosts: bhyvecloud
  remote_user: openbsd


  tasks:

    - name: install autoconf
      remote_user: root
      openbsd_pkg:
        name: autoconf--%2.69
        state: present
      become: yes

    - name: install automake 1.16
      remote_user: root
      openbsd_pkg:
        name: automake--%1.16
        state: present
      become: yes


    - name: install git
      remote_user: root
      openbsd_pkg:
        name: git
        state: present
      become: yes

    - name: install node js intepreter
      remote_user: root
      openbsd_pkg:
        name: node
        state: present
      become: yes

    - name: Add the user cryptpad for building this service
      remote_user: root
      ansible.builtin.user:
          name: cryptpad
          comment: user for building and managing such service
          groups: wheel
          shell: /bin/ksh
      become: yes

    - name: clone cryptpad repo
      remote_user: root
      git:
          version: main
          repo: https://github.com/xwiki-labs/cryptpad
          dest: /usr/home/cryptpad/cryptpad
      become: yes
      become_method: doas

    - name: chown cryptpad repo to cryptpad user
      remote_user: root
      file:
          path: /usr/home/cryptpad/cryptpad
          state: directory
          recurse: yes
          owner: cryptpad
      become: yes
      become_method: doas
