- hosts: bhyvecloud
  remote_user: openbsd


  tasks:

    - name: install autoconf
      remote_user: root
      openbsd_pkg:
        name: autoconf--%2.69
        state: present
      become: yes

    - name: install automake 1.16
      remote_user: root
      openbsd_pkg:
        name: automake--%1.16
        state: present
      become: yes


    - name: install git
      remote_user: root
      openbsd_pkg:
        name: git
        state: present
      become: yes

    - name: install node js intepreter
      remote_user: root
      openbsd_pkg:
        name: node
        state: present
      become: yes
    - name: clone cryptpad repo
      remote_user: root
      git:
          version: main
          repo: https://github.com/xwiki-labs/cryptpad
          dest: /usr/home/openbsd/cryptpad
      become: yes

    - name: copy cryptpad repository
      remote_user: root
      copy:
        src: /usr/home/openbsd/cryptpad
        dest: /var/www/cryptpad
        remote_src: yes
        owner: www
        group: daemon
        mode: u=rwx,g=xr,o=x
      become: yes

# And then we copy config.js from master machine to /var/www
